default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.22
    hooks:
      - id: ruff
        args: [--fix]
        files: '^(src|tests)/.*\.py$'
      - id: ruff-format
        files: '^(src|tests)/.*\.py$'
