"""Integration regression tests for non-admin connector access (issue #268).

Unit-level coverage lives in ``tests/test_connectors_auth.py`` where the
auth context is injected directly.  These tests go one layer deeper: they
run the **real** authentication chain — a user row in PostgreSQL, a real
JWT signed with the app's secret, the ``get_current_user`` DB lookup and
the ``require_permission("connectors", read)`` guard — through the FastAPI
app against the ephemeral PG/Redis harness shared by the integration suite.

Regression under test (issue #268): the connectors page loads
``GET /connectors/degiro-pension/imports`` in parallel with the other
connectors endpoints.  That endpoint used to be guarded by the hard-coded
``require_role("admin")`` dependency, so an authenticated principal with
role ``user`` (e.g. ``qa@finance-sync.local``) got
"Required one of roles ('admin',), got 'user'" and the whole page failed.

Acceptance criteria covered here:

* a real non-admin user with role ``user`` gets a 2xx on the connectors
  list endpoints (configs + DEGIRO import runs),
* an anonymous request is still rejected with 401.
"""

# pyright: basic

from __future__ import annotations

from typing import TYPE_CHECKING, Any

import httpx
import pytest

from finance_sync.app import create_app
from finance_sync.config.settings import Settings
from finance_sync.container import Container
from finance_sync.db.uow import UnitOfWork
from finance_sync.models import Tenant, User
from finance_sync.models.enums import UserRole
from finance_sync.services.auth import create_access_token, hash_password

if TYPE_CHECKING:
    from collections.abc import AsyncGenerator

    from fastapi import FastAPI
    from sqlalchemy.ext.asyncio import AsyncEngine, async_sessionmaker

pytestmark = pytest.mark.integration

# Fixed crypto material so JWTs are deterministic within the suite.
_INT_SECRET = "integration-test-secret-key-32chars!!"
_INT_MASTER_KEY = "0123456789abcdef" * 4  # 32 bytes hex

_CONFIGS_URL = "/api/v1/connectors/configs"
_IMPORTS_URL = "/api/v1/connectors/degiro-pension/imports"


@pytest.fixture
def auth_settings(
    database_url: str,
    redis_url: str,
) -> Settings:
    """Settings pointing the app at the ephemeral harness PG/Redis."""
    return Settings(
        database_url=database_url,  # pyright: ignore[reportArgumentType]
        redis_url=redis_url,  # pyright: ignore[reportArgumentType]
        secret_key=_INT_SECRET,  # pyright: ignore[reportArgumentType]
        master_encryption_key=_INT_MASTER_KEY,  # pyright: ignore[reportArgumentType]
    )


@pytest.fixture
def auth_container(
    auth_settings: Settings,
    pg_engine: AsyncEngine,
    session_factory: async_sessionmaker,
) -> Container:
    """DI container bound to the harness engine (NullPool, loop-safe)."""
    container = Container.from_settings(auth_settings)
    # Reuse the harness engine/session factory exactly like the e2e suite
    # does — same settings, loop-safe connection handling.
    container._engine = pg_engine  # pyright: ignore[reportPrivateUsage]
    container._session_factory = session_factory  # pyright: ignore[reportPrivateUsage]
    return container


@pytest.fixture
def auth_app(auth_settings: Settings, auth_container: Container) -> FastAPI:
    """FastAPI app with the container attached (lifespan not run)."""
    app = create_app(settings=auth_settings)
    app.state.container = auth_container
    return app


@pytest.fixture
async def auth_client(
    auth_app: FastAPI,
) -> AsyncGenerator[httpx.AsyncClient, None]:
    """Async HTTP client against the in-process app."""
    transport = httpx.ASGITransport(app=auth_app)
    async with httpx.AsyncClient(
        transport=transport, base_url="http://integration"
    ) as client:
        yield client


async def _seed_user(
    session_factory: async_sessionmaker,
    *,
    role: UserRole,
    email: str = "qa@finance-sync.local",
) -> dict[str, Any]:
    """Persist a tenant + user and return a real signed JWT for them."""
    async with session_factory() as session:
        async with UnitOfWork(session) as uow:
            tenant = await uow.tenants.add(
                Tenant(slug=f"qa-{role}", name=f"QA {role} tenant")
            )
            user = User(
                email=email,
                tenant_id=str(tenant.id),
                hashed_password=hash_password("integration-password"),
                display_name=f"QA {role}",
                role=role,
                is_active=True,
            )
            uow.session.add(user)
        # UnitOfWork commits on exit; ids are generated by then.
        tenant_id = str(tenant.id)
        user_id = str(user.id)

    token = create_access_token(
        {"sub": user_id, "tenant_id": tenant_id, "role": role},
        Settings(
            secret_key=_INT_SECRET,  # pyright: ignore[reportArgumentType]
        ),
    )
    return {
        "tenant_id": tenant_id,
        "user_id": user_id,
        "headers": {"Authorization": f"Bearer {token}"},
    }


# ── GET /connectors/configs ──────────────────────────────────────────


async def test_connectors_configs_ok_for_user_role(
    auth_client: httpx.AsyncClient,
    session_factory: async_sessionmaker,
) -> None:
    """A real non-admin user (role ``user``) can list connector configs.

    Regression: before the fix this endpoint already used the permission
    system, so the user role was allowed; this test pins that contract
    end-to-end through the real JWT + DB authentication chain.
    """
    seeded = await _seed_user(session_factory, role=UserRole.USER)
    resp = await auth_client.get(_CONFIGS_URL, headers=seeded["headers"])
    assert resp.status_code == 200
    assert resp.json() == []  # fresh tenant, no saved configs


async def test_connectors_configs_rejects_anonymous(
    auth_client: httpx.AsyncClient,
) -> None:
    """No credentials → 401 on connector configs listing."""
    resp = await auth_client.get(_CONFIGS_URL)
    assert resp.status_code == 401


# ── GET /connectors/degiro-pension/imports ───────────────────────────


async def test_degiro_import_runs_ok_for_user_role(
    auth_client: httpx.AsyncClient,
    session_factory: async_sessionmaker,
) -> None:
    """Regression test for issue #268.

    The connectors page loads this endpoint in parallel with the others.
    Before the fix it was guarded by ``require_role("admin")`` and a user
    with role ``user`` got 403 with "Required one of roles ('admin',),
    got 'user'" — taking the whole page down.  A real JWT for a role-``user``
    principal must now get a 2xx.
    """
    seeded = await _seed_user(session_factory, role=UserRole.USER)
    resp = await auth_client.get(_IMPORTS_URL, headers=seeded["headers"])
    assert resp.status_code == 200
    assert resp.json() == []  # fresh tenant, no import runs


async def test_degiro_import_runs_rejects_anonymous(
    auth_client: httpx.AsyncClient,
) -> None:
    """No credentials → 401 on DEGIRO import runs listing."""
    resp = await auth_client.get(_IMPORTS_URL)
    assert resp.status_code == 401
